name: Deploy React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./votacion-nacional

      - name: Build app
        run: npm run build
        working-directory: ./votacion-nacional

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: WebAppVotacion
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./votacion-nacional/build
